# Carregando as bibliotecas

In [ ]:
import pandas as pd # Pandas para carregamento do conjunto de dados

In [ ]:
from sklearn.preprocessing import LabelEncoder # Usada para codificação das categorias em números

In [ ]:
# Algoritmos usados para treinamento e predição

from sklearn.tree import DecisionTreeClassifier        # Árvore de Decisão
from sklearn.ensemble import RandomForestClassifier    # Floresta Aleatória
from sklearn.neighbors import KNeighborsClassifier     # KNN
from sklearn.svm import SVC                            # SVM
from sklearn.naive_bayes import GaussianNB             # Naive Bayes 
from sklearn.neural_network import MLPClassifier       # Rede Neural Artificial
from sklearn.linear_model import LogisticRegression    # Regressão Logística

In [ ]:
# Métricas para avaliação dos modelos
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix

In [ ]:
# Método para separação do conjunto em treino e teste
from sklearn.model_selection import train_test_split

In [1]:
# Biblioteca para salvamento dos codificadores e do modelo que apresentar melhor resultados
from sklearn.externals import joblib

C:\Users\ocean\Anaconda3\envs\web_ml\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
C:\Users\ocean\Anaconda3\envs\web_ml\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


# Definindo função para treinamento e avaliação dos algoritmos

In [10]:
def train_test_clf(clf, X, y):
    
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)
    
    clf.fit(X_train, y_train)

    y_pred = clf.predict(X_test)

    print(accuracy_score(real, predicts))
    print(confusion_matrix(real, predicts))
    print(classification_report(real, predicts))

# Carregamento e Análise do conjunto de dados

In [2]:
df = pd.read_csv('patientdataV6.csv') # Carregando o conjunto de dados na memória

In [3]:
df.head() # Verificando os 5 primeiros exemplos do conjunto

AVGHEARTBEATSPERMIN  PALPITATIONSPERDAY  CHOLESTEROL  BMI HEARTFAILURE  \
0                   93                  22          163   25            N   
1                  108                  22          181   24            N   
2                   86                   0          239   20            N   
3                   80                  36          164   31            Y   
4                   66                  36          185   23            N   

   AGE SEX FAMILYHISTORY SMOKERLAST5YRS  EXERCISEMINPERWEEK  
0   49   F             N              N                 110  
1   32   F             N              N                 192  
2   60   F             N              N                 121  
3   45   F             Y              N                 141  
4   39   F             N              N                  63

In [4]:
df.info() # Verificando algumas informações gerais do conjunto de dados

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10800 entries, 0 to 10799
Data columns (total 10 columns):
AVGHEARTBEATSPERMIN    10800 non-null int64
PALPITATIONSPERDAY     10800 non-null int64
CHOLESTEROL            10800 non-null int64
BMI                    10800 non-null int64
HEARTFAILURE           10800 non-null object
AGE                    10800 non-null int64
SEX                    10800 non-null object
FAMILYHISTORY          10800 non-null object
SMOKERLAST5YRS         10800 non-null object
EXERCISEMINPERWEEK     10800 non-null int64
dtypes: int64(6), object(4)
memory usage: 843.9+ KB


In [5]:
df.HEARTFAILURE.value_counts() # Contagem da distribuição das características alvo

N    9012
Y    1788
Name: HEARTFAILURE, dtype: int64

In [9]:
df.corr()

AVGHEARTBEATSPERMIN  PALPITATIONSPERDAY  CHOLESTEROL  \
AVGHEARTBEATSPERMIN             1.000000            0.006528     0.005837   
PALPITATIONSPERDAY              0.006528            1.000000     0.008507   
CHOLESTEROL                     0.005837            0.008507     1.000000   
BMI                             0.050005            0.031096     0.011770   
HEARTFAILURE                    0.218694            0.054420     0.016542   
AGE                            -0.001936            0.009795    -0.012401   
SEX                            -0.002783            0.000794     0.004805   
FAMILYHISTORY                   0.153367            0.041322     0.006940   
SMOKERLAST5YRS                  0.029828            0.008423     0.002050   
EXERCISEMINPERWEEK             -0.019575           -0.009556    -0.008601   

                          BMI  HEARTFAILURE       AGE       SEX  \
AVGHEARTBEATSPERMIN  0.050005      0.218694 -0.001936 -0.002783   
PALPITATIONSPERDAY   0.031096      0.054420  0.009795  0.000794   
CHOLESTEROL          0.011770      0.016542 -0.012401  0.004805   
BMI                  1.000000      0.136222 -0.005033 -0.005911   
HEARTFAILURE         0.136222      1.000000 -0.017005 -0.007444   
AGE                 -0.005033     -0.017005  1.000000 -0.000172   
SEX                 -0.005911     -0.007444 -0.000172  1.000000   
FAMILYHISTORY        0.087891      0.399565 -0.014516  0.002176   
SMOKERLAST5YRS       0.003152      0.081169  0.003387 -0.010618   
EXERCISEMINPERWEEK  -0.035000     -0.085311 -0.013585  0.014572   

                     FAMILYHISTORY  SMOKERLAST5YRS  EXERCISEMINPERWEEK  
AVGHEARTBEATSPERMIN       0.153367        0.029828           -0.019575  
PALPITATIONSPERDAY        0.041322        0.008423           -0.009556  
CHOLESTEROL               0.006940        0.002050           -0.008601  
BMI                       0.087891        0.003152           -0.035000  
HEARTFAILURE              0.399565        0.081169           -0.085311  
AGE                      -0.014516        0.003387           -0.013585  
SEX                       0.002176       -0.010618            0.014572  
FAMILYHISTORY             1.000000        0.053356           -0.053195  
SMOKERLAST5YRS            0.053356        1.000000           -0.009926  
EXERCISEMINPERWEEK       -0.053195       -0.009926            1.000000

# Preparando codificadores das características categóricas

In [6]:
# Definindo codificadores
hf_encoder = LabelEncoder()
sex_encoder = LabelEncoder()
family_encoder = LabelEncoder()
smoker_encoder = LabelEncoder()

In [7]:
# Preparando codificadores para as variáveis categóricas
df.HEARTFAILURE = hf_encoder.fit_transform(df.HEARTFAILURE)
df.SEX = sex_encoder.fit_transform(df.SEX)
df.FAMILYHISTORY = family_encoder.fit_transform(df.FAMILYHISTORY)
df.SMOKERLAST5YRS = smoker_encoder.fit_transform(df.SMOKERLAST5YRS)

In [8]:
# Salvando codificadores
joblib.dump(hf_encoder, 'hf_encoder.pkl')
joblib.dump(sex_encoder, 'sex_encoder.pkl')
joblib.dump(family_encoder, 'family_encoder.pkl')
joblib.dump(smoker_encoder, 'smoker_encoder.pkl')

['smoker_encoder.pkl']

In [20]:
df.head()

AVGHEARTBEATSPERMIN  PALPITATIONSPERDAY  CHOLESTEROL  BMI  HEARTFAILURE  \
0                   93                  22          163   25             0   
1                  108                  22          181   24             0   
2                   86                   0          239   20             0   
3                   80                  36          164   31             1   
4                   66                  36          185   23             0   

   AGE  SEX  FAMILYHISTORY  SMOKERLAST5YRS  EXERCISEMINPERWEEK  
0   49    0              0               0                 110  
1   32    0              0               0                 192  
2   60    0              0               0                 121  
3   45    0              1               0                 141  
4   39    0              0               0                  63

# Separando o conjunto em variáveis preditoras (X) e variável alvo (y)

In [11]:
X = df.drop(['HEARTFAILURE'], axis=1).values
y = df.HEARTFAILURE.values

# Usando função de treinamento e avaliação para os diferentes algoritmos

In [12]:
train_test_clf(DecisionTreeClassifier(), X, y) # Árvore de Decisão

0.7925925925925926
[[1550  239]
 [ 209  162]]
              precision    recall  f1-score   support

           0       0.88      0.87      0.87      1789
           1       0.40      0.44      0.42       371

    accuracy                           0.79      2160
   macro avg       0.64      0.65      0.65      2160
weighted avg       0.80      0.79      0.80      2160



In [13]:
train_test_clf(RandomForestClassifier(), X, y) # Floresta Aleatória

C:\Users\ocean\Anaconda3\envs\web_ml\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


0.8560185185185185
[[1709   58]
 [ 253  140]]
              precision    recall  f1-score   support

           0       0.87      0.97      0.92      1767
           1       0.71      0.36      0.47       393

    accuracy                           0.86      2160
   macro avg       0.79      0.66      0.70      2160
weighted avg       0.84      0.86      0.84      2160



In [14]:
train_test_clf(KNeighborsClassifier(), X, y) # KNN

0.8375
[[1763   65]
 [ 286   46]]
              precision    recall  f1-score   support

           0       0.86      0.96      0.91      1828
           1       0.41      0.14      0.21       332

    accuracy                           0.84      2160
   macro avg       0.64      0.55      0.56      2160
weighted avg       0.79      0.84      0.80      2160



In [15]:
train_test_clf(SVC(), X, y) # SVM

C:\Users\ocean\Anaconda3\envs\web_ml\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


0.8356481481481481
[[1805    0]
 [ 355    0]]
              precision    recall  f1-score   support

           0       0.84      1.00      0.91      1805
           1       0.00      0.00      0.00       355

    accuracy                           0.84      2160
   macro avg       0.42      0.50      0.46      2160
weighted avg       0.70      0.84      0.76      2160



C:\Users\ocean\Anaconda3\envs\web_ml\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [16]:
train_test_clf(GaussianNB(), X, y) # Naive Bayes

0.8245370370370371
[[1570  221]
 [ 158  211]]
              precision    recall  f1-score   support

           0       0.91      0.88      0.89      1791
           1       0.49      0.57      0.53       369

    accuracy                           0.82      2160
   macro avg       0.70      0.72      0.71      2160
weighted avg       0.84      0.82      0.83      2160



In [17]:
train_test_clf(MLPClassifier(), X, y) # Rede Neural Artificial

0.8462962962962963
[[1666  132]
 [ 200  162]]
              precision    recall  f1-score   support

           0       0.89      0.93      0.91      1798
           1       0.55      0.45      0.49       362

    accuracy                           0.85      2160
   macro avg       0.72      0.69      0.70      2160
weighted avg       0.84      0.85      0.84      2160



In [18]:
train_test_clf(LogisticRegression(), X, y) # Regressão Logística

C:\Users\ocean\Anaconda3\envs\web_ml\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


0.8611111111111112
[[1755   38]
 [ 262  105]]
              precision    recall  f1-score   support

           0       0.87      0.98      0.92      1793
           1       0.73      0.29      0.41       367

    accuracy                           0.86      2160
   macro avg       0.80      0.63      0.67      2160
weighted avg       0.85      0.86      0.83      2160



# Salvando melhor classificador 

In [19]:
clf = RandomForestClassifier()
clf.fit(X, y)
joblib.dump(clf, 'rf.pkl')

C:\Users\ocean\Anaconda3\envs\web_ml\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


['rf.pkl']